services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/title-tracker/backend:latest
    container_name: title_tracker_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tt_network

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/title-tracker/frontend:latest
    container_name: title_tracker_frontend
    restart: always
    environment:
      - VITE_DISABLE_DEVTOOLS=true
    networks:
      - tt_network

  nginx:
    image: nginx:alpine
    container_name: title_tracker_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static:ro
    depends_on:
      - backend
      - frontend
    networks:
      - tt_network

  db:
    image: postgres:18-alpine
    container_name: title_tracker_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bugweaver -d title_tracker" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - tt_network

  redis:
    image: redis:alpine
    container_name: title_tracker_redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - tt_network

networks:
  tt_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  static_volume:
